# Generated by Django 6.0.1 on 2026-05-11 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('auto_extend_time', models.PositiveIntegerField(default=0, help_text='Minutes to auto-extend when a bid is placed near the end (0 = disabled)')),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='upcoming', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_bids', models.PositiveIntegerField(default=0)),
                ('total_watchers', models.PositiveIntegerField(default=0)),
                ('winning_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='artworks.artwork')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_auctions', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_bids', models.PositiveIntegerField(default=0)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='auctions.auction')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Result',
                'verbose_name_plural': 'Auction Results',
                'ordering': ('-sold_at',),
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bid_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_winning_bid', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ('-bid_amount', '-bid_time'),
            },
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Auction Created'), ('bid_placed', 'Bid Placed'), ('bid_cancelled', 'Bid Cancelled'), ('started', 'Auction Started'), ('ended', 'Auction Ended'), ('sold', 'Auction Sold'), ('reserve_met', 'Reserve Met'), ('extended', 'Auction Extended'), ('winner', 'Winner Determined')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='auctions.auction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bid Histories',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='AuctionWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Watchlist',
                'verbose_name_plural': 'Auction Watchlists',
                'ordering': ('-added_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'auction'), name='unique_user_auction_watch')],
            },
        ),
    ]
